### ISSUE TITLE
Inference for the images other than 299x299 resolution

### ISSUE THREAD

**Issue by hyeokhyen** [alexvbogdan/DeepCalib#1]
Hi.

How do you test the images with different size and aspect ratio?
The inference code (https://github.com/alexvbogdan/DeepCalib/blob/master/prediction/Classification/Single_net/predict_classifier_dist_focal.py) seems to simple resize the image to 299x299 resolution.

Wouldn't it distort the image significantly if the aspect ratio is far from 1:1?

I will appreciate your reply.

**Comment by alexvbogdan** [comment]
Hi Alan,

In short, no it would not.
When you predict the focal length for an image of arbitrary size you have
to resize it to 299x299. When you will use the focal length for your
application of interest you only need to multiply the focal length by the
ratio original_width/299 (in case height > width: original_height/299).
Distortion parameter remains unchanged.

All the best,
Alex
