### ISSUE TITLE
Missing others.txt file

### ISSUE THREAD

**Issue by snowzhangy** [alexvbogdan/DeepCalib#11]
Trying the download dataset script. but stopped at others.txt is missing.

**Comment by alexvbogdan** [comment]
Sorry, but could you specify the problem? others.txt file is there for both indoors and outdoors folders. Also, check #2 for more information, the Sun360 dataset is unavailable at the moment. 

However, if you managed to download some parts of this dataset then tell me, please.

**Comment by snowzhangy** [comment]
hi Alex:
   from the download script
`   down_from_dir("./indoor")
    down_from_dir("./outdoor")
    down_from_txt("others.txt")
`
   The last others.txt should be in dataset dir.

**Comment by alexvbogdan** [comment]
Ok, I saw this too, I cannot find the others.txt file for now but I added the Google Drive link to Readme. You can use it to download the sun360 dataset manually. Hope this helps.

Can you tell me if `down_from_dir("./indoor")` worked because other people complained it is not working?

**Comment by snowzhangy** [comment]
the script works fine . just won't download since the server is down.

**Comment by alexvbogdan** [comment]
Ok, I see, that is the same problem as it was before. Anyway, I just checked the Google Drive link, the dataset is there, so you can download it.
