### ISSUE TITLE
num of train data

### ISSUE THREAD

**Issue by MinjingLin** [alexvbogdan/DeepCalib#15]
I have downloaded the SUN360 dataset from google drive, but there only has 446 images in train folder. I note that the line 59 in [https://github.com/alexvbogdan/DeepCalib/blob/master/dataset/discrete_dataset_generation.py](url) is set 1 for every image.Therefor, I only got 446 discrete samples for training.

can I ask what is the total num was set for training data?

**Comment by alexvbogdan** [comment]
Hi Minjing,

As far as I remember we generated 10 images per one pano. Although, it is totally up to you. The most important thing is that there is not too much overlap between images. We found out 10 is an appropriate number. If you want more/less images you can experiment with per pano generated images number and see if they overlap.

**Comment by MinjingLin** [comment]
> Hi Minjing,
> 
> As far as I remember we generated 10 images per one pano. Although, it is totally up to you. The most important thing is that there is not too much overlap between images. We found out 10 is an appropriate number. If you want more/less images you can experiment with per pano generated images number and see if they overlap.

Thanks for your prompt reply!
