### ISSUE TITLE
Normalization of the focal length

### ISSUE THREAD

**Issue by JanOS92** [alexvbogdan/DeepCalib#18]
Hi,
first of all: Thank you for sharing this implementation!
 
During some adaptions of the code I was wondering about the normalization of <img src="https://render.githubusercontent.com/render/math?math=f">. For example row 60 in **train_regressor_dist_focal.py** says:
`labels_focal_train.append((curr_parameter - focal_start*1.) / (focal_end*1.+1. - focal_start*1.)) #normalize bewteen 0 and 1`
Shouldn't it be:
`labels_focal_train.append((curr_parameter - focal_start*1.) / (focal_end*1. - focal_start*1.)) #normalize bewteen 0 and 1`
Or am I missing something?

Many thanks!

**Comment by alexvbogdan** [comment]
Hello,

Yes, you are right, this is a typo. I will change it asap.
Thank you for pointing it out!
