### ISSUE TITLE
Problem with the prediction of the Single_Net Classifier

### ISSUE THREAD

**Issue by sidoodler** [alexvbogdan/DeepCalib#19]
I tried running the file **predict_classifier_dist_focal.py** which uses the Single_net architecture without making any changes that could affect the output, but still, every time I ran the code, it outputted the last value of **classes_focal** as the focal length. To confirm this, I changed **classes_focal** many times so that it contained a wide variety of different values each time, but still, the code just outputted the last value of **classes_focal**.

Can someone explain how this result is possible?

Thank you very much in advance!!

**Comment by rameau-fr** [comment]
Hello, in what context does it happen? 
During training or testing? 
Have you try inference with pre-trained weights? On what images do you get such kind of results? Have you tried with large field of view images like fisheye ?
