### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by sharan21** [alexvbogdan/DeepCalib#2]
http://sun360.csail.mit.edu seems to be down in my region, is there any alternate domain or source from which I can download the dataset?

**Comment by alexvbogdan** [comment]
This is what I found on their official website.
**To download the panoramas at various resolutions (we have up to 9104x4552 resolution), please email Jianxiong Xiao**: jxiao@mit.edu.
Please tell me if you downloaded it successfully.

**Comment by sharan21** [comment]
The first email could not be sent and gave me this error: 550 5.4.1 Recipient address rejected: Access denied. AS(201806281), waiting for a response from the second email. Another person told me that the database went down due to trademark issues, not sure how true that statement is.

On another unrelated note, I am more interested in reproducing the auto undistortion/ 3D reconstruction section of the paper, which I cannot seem to find the script for. Has it been included in this repo? If so please point me to the file to run.

**Comment by alexvbogdan** [comment]
I will add a MATLAB code for undistortion soon. Regarding 3D reconstruction, we used COLMAP software and did not write our own code for that part.
Also, there exists another dataset with 360 panoramic images: https://vcl.iti.gr/360-dataset/. Thank you for pointing out the problem of downloading the sun360 dataset.

**Comment by sharan21** [comment]
Thanks, please add all relevant code/ documentation for COLMAP usage etc, since that is pretty much the novel use case of the paper.

**Comment by thanif** [comment]
> I will add a MATLAB code for undistortion soon. Regarding 3D reconstruction, we used COLMAP software and did not write our own code for that part.
> Also, there exists another dataset with 360 panoramic images: https://vcl.iti.gr/360-dataset/. Thank you for pointing out the problem of downloading the sun360 dataset.

Thanks.

**Comment by sagocz** [comment]
Have any of you gained access to the SUN360 dataset?

**Comment by thanif** [comment]
Yes, a part of it is available here:
https://github.com/ChaoningZhang/DeepPTZ

**Comment by cyjouc** [comment]
> This is what I found on their official website.
> **To download the panoramas at various resolutions (we have up to 9104x4552 resolution), please email Jianxiong Xiao**: [jxiao@mit.edu](mailto:jxiao@mit.edu) or [profxoffice@autox.ai](mailto:profxoffice@autox.ai)
> Please tell me if you downloaded it successfully.

Hi ,I fail to the email,can you download it successfully?would you like share?

**Comment by alexvbogdan** [comment]
Hello, no we do not possess this dataset. This email is not maintained anymore, and generally I do not think that SUN360 is available online anymore. You can find other sources of 360 panoramic images in [here](https://github.com/alexvbogdan/DeepCalib#dataset-generation).

**Comment by YYaHan** [comment]
Hi, I can not download 360 panoramic images in Dataset Generation section. Can you share the images?

> Hello, no we do not possess this dataset. This email is not maintained anymore, and generally I do not think that SUN360 is available online anymore. You can find other sources of 360 panoramic images in [Dataset Generation section](https://github.com/alexvbogdan/DeepCalib#dataset-generation).

**Comment by Everloom-129** [comment]
Hi! The links above seems expired, could we fetch sun360 anywhere now?
