### ISSUE TITLE
Undistorting a new image

### ISSUE THREAD

**Issue by manavsingh415** [alexvbogdan/DeepCalib#20]
Hi

I used the Single Net classifier weights that are available in the google drive to create a txt file using the predict_classifier_dist_focal.py script. Then, I used the matlab code undist_from_txt.m to create the undistorted image. I made sure that the input image to both these scripts had shape (299, 299, 3), yet this is the output I am getting.

Input:
![resized_frame](https://user-images.githubusercontent.com/52657412/128634178-3843c6a4-1c17-4649-ac70-ce8b597b3760.png)

Output:
![image](https://user-images.githubusercontent.com/52657412/128634155-4e3f5df0-1b7b-4b5a-a834-9e683560e1bc.jpg)

In the txt file, prediction_focal = 490 and prediction_dist = 0.72

Any help would be appreciated! Thanks

**Comment by rameau-fr** [comment]
Hello,

I downloaded your picture and tried with the obtained parameters from this code (note that I set the new focal as 1.5 times the predicted one to avoid too much black margins):

`
%undistort image
clear all; close all; clc

% image
Idis = imread("Image_DeepCalib.png")

%parameters
focal = 490;
xi =  0.72
[ImH,ImW,~] = size(Idis);
f_dist = focal * (ImW/ImH) * (ImH/299); % focal length
u0_dist = ImW/2;
v0_dist = ImH/2;
Paramsd.f = f_dist;
Paramsd.W = u0_dist*2;  
Paramsd.H = v0_dist*2;
Paramsd.xi = xi;
Paramsund.f = f_dist*1.5;
Paramsund.W = u0_dist*2;  
Paramsund.H = v0_dist*2;

Image_und = undistSphIm(Idis, Paramsd, Paramsund);
imshow(Image_und,[])
`

here is the obtained results:
![][https://pasteboard.co/Kf0IGYl.jpg]

it looks okay, but I can still see some radial distortion left on the right side of the image. I wonder if the radial distortion center is located in the middle of the image (it is a strong assumption of DeepCalib).

Best,

**Comment by manavsingh415** [comment]
Hi

This is great! Thank you :)
