### ISSUE TITLE
Are the original test image in Table 1 available?

### ISSUE THREAD

**Issue by loong8888** [alexvbogdan/DeepCalib#21]
Hi, thanks for your great work! It helps me a lot.
We plan to cite your work and compare our results with yours, but can not repeat the metrics in Table 1, since we do not have the same test images in table 1. Is there any possibility that we could download them somewhere?
Thanks!

**Comment by alexvbogdan** [comment]
Sorry, we downloaded them online and now we don't possess them anymore. I suggest you do that on any other images, it should give you a fair comparison with your method.
Thank you for your interest in our work!
