### ISSUE TITLE
Calculating mapping given focal length and distortion parameter

### ISSUE THREAD

**Issue by manavsingh415** [alexvbogdan/DeepCalib#22]
Hi! 

If I have a point with pixel coordinates (x,y) in an image (distorted), and I have the focal length and distortion parameter of the camera using your weights, do you have a function in python that takes these inputs (pixel coordinates, focal length, distortion param) and outputs the pixel coordinates of the projected point in the undistorted image?

Thanks

**Comment by alexvbogdan** [comment]
Hello,
Yes, we have this code but only in [MATLAB](https://github.com/alexvbogdan/DeepCalib/blob/master/undistortion/undistSphIm.m) unfortunately. Although, for a single point you could easily rewrite it to python.
