### ISSUE TITLE
Number of classes for local length

### ISSUE THREAD

**Issue by LeonhardEulerr** [alexvbogdan/DeepCalib#26]
Hello, 

Firstly, thanks for an amazing work put into this project.

I try to load your pre-trained weights into your model and I get:
![image](https://user-images.githubusercontent.com/73944828/153412605-f1761eec-a319-4a9c-9bd6-25a1a66a5fa3.png)

Are you sure you did not have any other range for focal length when setting up the model? Seems like you had one more value in it.

Edit:
When adding one more value to `classes_focal` (I added 510) it seems to work fine when loading the weights but I assume it is better to know what classes you had exactly when setting up the project so that we can reproduce the results. 

Edit2:
I see that in prediction code you used range for focal length (40,501,10). In the training code though you used (50,501,10) so I guess it is safe to assume that training could be done on (40,501,10) as well.

**Comment by alexvbogdan** [comment]
Hi, sorry for such a long reply. Yes, you are right the weight that we uploaded used (40, 501, 10) classes, that is an error. I will correct it, thank you for finding it!
