### ISSUE TITLE
Can I use your package in my start-up project for commercialization?

### ISSUE THREAD

**Issue by TanNhuNguyen** [alexvbogdan/DeepCalib#28]

**Comment by rameau-fr** [comment]
Hello,

this work is protected by the following US patent: [[1]](https://patentimages.storage.googleapis.com/c2/0b/d9/812b61f2ec8fc0/US10977831.pdf)
Another similar work estimating the focal and attitude of a camera from a single image has been similarly patented: [[2]](https://patentimages.storage.googleapis.com/a3/ea/e8/603e21f7b5c8e6/US10515460B2.pdf),
[[3]](https://patentimages.storage.googleapis.com/a5/be/45/155758ee7eb7c7/US10964060.pdf)

Therefore, it seems that you would have to first deal with some legal issues before you can commercialize these solutions :-s. I hope it helps.
 
Best regards
