### ISSUE TITLE
Why in undistSphIm.m xi1 is equal zero?

### ISSUE THREAD

**Issue by InfiniteLife** [alexvbogdan/DeepCalib#29]
here:

https://github.com/alexvbogdan/DeepCalib/blob/b9b5fc3bac8d9845c9d8172b80833c6bc86492a2/undistortion/undistSphIm.m#L28-L31

is it supposed to be predicted distortion coefficient or is it just 0? I dont understand why we are having trouble to square 0 and multiply previously created arrays by zero.

**Comment by alexvbogdan** [comment]
Thank you for pointing it out, it is just a redundancy. Everything is correct in that code.
