### ISSUE TITLE
radial distortion

### ISSUE THREAD

**Issue by KOuldamer** [alexvbogdan/DeepCalib#30]
Hi, 

Is it possible to generate radial distored images to estimate k1, k2 parameters using this model ?

**Comment by alexvbogdan** [comment]
Hi,
Our model outputs a single distortion parameter that can be interpreted using the unified spherical model. To my best knowledge, there is no way to convert the spherical model distortion parameter to the Brown model (I assume that is what you mean).
If you are asking if you can generate an image using our model, then no. It is not a GAN or anything of the kind, although it would be a very interesting approach to estimate radial distortion.
