### ISSUE TITLE
what should I put in valid path?

### ISSUE THREAD

**Issue by xanywy** [alexvbogdan/DeepCalib#32]
Should I put the test data in valid path and the train data in train path? (In code network_training/Regression/Single_net/train_regressor_dist_focal.py)

**Comment by alexvbogdan** [comment]
Yes, you those are the paths to your training and validation datasets.
You can split your data in any way you see fit. My advice is to reserve a portion of the dataset for a test that was not used during the training for an unbiased evaluation.
