### ISSUE TITLE
Trouble with OpenCV undistortion

### ISSUE THREAD

**Issue by sharan21** [alexvbogdan/DeepCalib#4]
I am trying to implement undistortion using openCV using the focal length and distortion parameters using cv2.undistort() and have passed the camera matrix, source image and distortion matrix as mentioned in the paper where Fx = Fy = F and p1, p2 = 0 (tangential distortion) and since there is only one distortion coefficient available, k1 = obtained distortion and k2 = 0.

Therefore the distortion matrix (k1, k2, p1, p2) = (k, 0, 0, 0). Taking these parameters I am not getting accurate undistorted images, am I doing anything wrong? Also I am unable to find any other mode of contact, can you please provide your email id if raising git issues is not appreciated.

**Comment by alexvbogdan** [comment]
Raising git issues is completely fine.

OpenCV undistortion function assumes Brown distortion model which indeed has 4 parameters to describe the distortion. In our work, we chose the unified spherical model which parametrizes camera distortion with a single value. If you want to undistort the image using our parameters you can use the MATLAB undistortion [code](https://github.com/alexvbogdan/DeepCalib/blob/master/undistortion) we provided. I also believe it can be easily converted to Python if that is crucial for you. Feel free to create a `pull request` if you are going to convert it.
