### ISSUE TITLE
substitute for interp2 matlab function in python

### ISSUE THREAD

**Issue by sharan21** [alexvbogdan/DeepCalib#5]
I have almost finished replicating both the matlab scripts in 'undistortion' folder in python but am facing a problem finding a substitute of the interp2 function used in undistSphIm.m in line 45.

You can find both my scripts here; https://github.com/sharan21/arvind-defect-detection

I am trying to use scipys interp2d function(https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html) but am running into an unexpected error:
OverflowError: Too many data points to interpolate , which I am having trouble debugging

I am not too sure about what interp2 does in your code and generally do not understand its documentation due to a lack of sufficient knowledge in this domain. Any suggestions and advise to complete my scripts is much appreciated, I will send a merge request to add the python scripts once its done

**Comment by alexvbogdan** [comment]
We have used [this](https://github.com/alexvbogdan/DeepCalib/blob/master/dataset/my_interpol.py) function as a substitution for MATLAB interp2 function for dataset generation. You can check its usage in [here](https://github.com/alexvbogdan/DeepCalib/blob/c99c86903cf94339615793694eaad35acda83ed9/dataset/discrete_dataset_generation.py#L139) for example.
