### ISSUE TITLE
my_interpol.interp2linear() for cubic interpolation

### ISSUE THREAD

**Issue by sharan21** [alexvbogdan/DeepCalib#6]
Like I said before in the previous issues I raised I am trying to recreate the matlab scripts for undistortion using python and took your suggestion in using my_interpol.interp2linear() to do so but I am getting incorrect results (the image is nearly empty and nonsensical)

It is my understanding that undistortion requires 'cubic' interpolation rather than 'linear' interpolation which is what my_interpol.interp2linear() seems to use. 

Is this occurring because I am not using 'cubic' interpolation? If so how do I approach modifying interp2linear for 'cubic' interpolation? Please refer to my code: https://github.com/sharan21/arvind-defect-detection

**Comment by alexvbogdan** [comment]
I am sorry I cannot help you with this one. Yes, MATLAB function `interp2` uses cubic interpolation indeed if that is of any help.

**Comment by alexvbogdan** [comment]
#5

**Comment by alexvbogdan** [comment]
"Duplicate of" #5
