### ISSUE TITLE
OpenCV requirement

### ISSUE THREAD

**Issue by Tetsujinfr** [alexvbogdan/DeepCalib#8]
Hi, thanks for your repo.
 I think you have forgotten to mention the opencv dependency in the readme requirements. Could you please indicate which version should be used ? (I have tried some recent version but I got some lib dependencies version incompatibilities error). Thanks for your help.

**Comment by Tetsujinfr** [comment]
I used the std pip install of opencv and opencv-contrib (installed versiin was 3.2.1) and all worked well in the end. So maybe be just add that detail to the requirements in the readme for sake of completness. I am closing the issue.

**Comment by alexvbogdan** [comment]
Thank you for the info!
